// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCH3KaHRgniOFWEMTIrrz3Qt1jVwmgVz9U',
    appId: '1:403038308387:web:cf51bb9d6fad2eb0508996',
    messagingSenderId: '403038308387',
    projectId: 'app-kasir-bacabox',
    authDomain: 'app-kasir-bacabox.firebaseapp.com',
    storageBucket: 'app-kasir-bacabox.appspot.com',
    measurementId: 'G-EH92X3JL9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp9jDJEJyMjIsF0RcuYAsSWCK0nJJHqGo',
    appId: '1:403038308387:android:426ab3887e333a61508996',
    messagingSenderId: '403038308387',
    projectId: 'app-kasir-bacabox',
    storageBucket: 'app-kasir-bacabox.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5cmNQLobvSbS2xJitlZMRikGTEtMPkzU',
    appId: '1:403038308387:ios:c330b568f8c8f5f3508996',
    messagingSenderId: '403038308387',
    projectId: 'app-kasir-bacabox',
    storageBucket: 'app-kasir-bacabox.appspot.com',
    iosBundleId: 'com.example.bacabox',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5cmNQLobvSbS2xJitlZMRikGTEtMPkzU',
    appId: '1:403038308387:ios:76d446ce4e796e62508996',
    messagingSenderId: '403038308387',
    projectId: 'app-kasir-bacabox',
    storageBucket: 'app-kasir-bacabox.appspot.com',
    iosBundleId: 'com.example.bacabox.RunnerTests',
  );
}
